{% set name = "finnhub-python" %}
{% set version = "2.4.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/finnhub-python-{{ version }}.tar.gz
  sha256: 5d50c5fa9b64b7bfe474f593322b3334cc56f9478c81ece915ce454a1771dff7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests >=2.22.0

test:
  imports:
    - finnhub
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://finnhub.io/docs/api
  summary: Finnhub API
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yehoshuadimarsky
