{% set name = "finnhub-python" %}
{% set version = "2.4.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 90ca51907792eea45dce3c524a95ba2a9a2473aad3a9096afac8d9edf40562f5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests >=2.22.0

test:
  imports:
    - finnhub
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://finnhub.io/docs/api
  summary: Finnhub API
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yehoshuadimarsky
